// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB38RSISDMwCoexoJAME71BULW-MQfQesA',
    appId: '1:202257059512:web:80604027ba52283a0a2e4d',
    messagingSenderId: '202257059512',
    projectId: 'silkspaceadmin',
    authDomain: 'silkspaceadmin.firebaseapp.com',
    storageBucket: 'silkspaceadmin.appspot.com',
    measurementId: 'G-J9GK0T3SGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-1rOsD2cXreCvGSAuM6DWwcJFhFIXOG4',
    appId: '1:202257059512:android:c6596d2c267a45d10a2e4d',
    messagingSenderId: '202257059512',
    projectId: 'silkspaceadmin',
    storageBucket: 'silkspaceadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9XT29Wj8BRkb3R9_i703LKXbiq75-A4w',
    appId: '1:202257059512:ios:a6c990503c9b797d0a2e4d',
    messagingSenderId: '202257059512',
    projectId: 'silkspaceadmin',
    storageBucket: 'silkspaceadmin.appspot.com',
    iosBundleId: 'com.example.silkspaceadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9XT29Wj8BRkb3R9_i703LKXbiq75-A4w',
    appId: '1:202257059512:ios:a6c990503c9b797d0a2e4d',
    messagingSenderId: '202257059512',
    projectId: 'silkspaceadmin',
    storageBucket: 'silkspaceadmin.appspot.com',
    iosBundleId: 'com.example.silkspaceadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB38RSISDMwCoexoJAME71BULW-MQfQesA',
    appId: '1:202257059512:web:d5b538bc476d76a90a2e4d',
    messagingSenderId: '202257059512',
    projectId: 'silkspaceadmin',
    authDomain: 'silkspaceadmin.firebaseapp.com',
    storageBucket: 'silkspaceadmin.appspot.com',
    measurementId: 'G-DQ3Q2E2FJ9',
  );
}
